CapStonePhase2/Models/Lectures.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapStonePhase2.Models
{
    public class Lectures
    {

        [Key]
        public int Id { get; set; }

        [Display(Name = "Topic:")]
        public string Topic { get; set; }

        [Display(Name = "Description:")]
        public string Description { get; set; }

        [Display(Name = "Review Question:")]
        public string ReviewQuestion { get; set; }

        [Display(Name = "Coded Example:")]
        public string CodeExample { get; set; }

        [Display(Name = "Code Assignment:")]
        public string CodeAssignment { get; set; }

        //Student Id placeholder
        public int StudentId { get; set; }

        public string CodeFileName { get; set; }

        public string CodeFileText { get; set; }

        public IList<Students_Lectures> Student_Lectures { get; set; }

    }
}

CapStonePhase2/Models/Students.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapStonePhase2.Models
{
    public class Students
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "First Name:")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name:")]
        public string LastName { get; set; }

        public string Userid { get; set; }

        //Lecture id placeholder
        public int Lectureid { get; set; }

        public IList<Students_Lectures> Students_Lecture { get; set; }
    }
}

CapStonePhase2/Controllers/InstructorsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CapStonePhase2.Models;
using Microsoft.AspNet.Identity;

namespace CapStonePhase2.Controllers
{
    public class InstructorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Instructors
        public ActionResult Index()
        {
            return View(db.Instructors.ToList());
        }

        public ActionResult GradeShortAnswer(int studentid, int lectureid)
        {
            var StudentAnswers = db.Students_Lectures.Include(x=>x.Lecture).Include(y=>y.Student).SingleOrDefault(z => z.StudentId == studentid && z.LectureId == lectureid);

            if (StudentAnswers == null)
            {
                return HttpNotFound();
            }

            return View(StudentAnswers);
        }

        public ActionResult ChangeGrade(int studentid, int lectureid)
        {
            var GradingStudent = db.Students_Lectures.SingleOrDefault(z => z.StudentId == studentid && z.LectureId == lectureid);

            if (GradingStudent == null)
            {
                return HttpNotFound();
            }

            if(GradingStudent.IsShortAnswerCorrect == false)
            {
                GradingStudent.IsShortAnswerCorrect = true;
            }
            else
            {
                GradingStudent.IsShortAnswerCorrect = false;
            }

            db.SaveChanges();

            CheckIfStudentPassed(GradingStudent);
            return RedirectToAction("GradeShortAnswer", new { studentid = studentid, lectureid = lectureid });
        }

        // GET: Instructors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructors instructors = db.Instructors.Find(id);
            if (instructors == null)
            {
                return HttpNotFound();
            }
            return View(instructors);
        }

        // GET: Instructors/Create
        public ActionResult Create()
        {
            Instructors NewInstructor = new Instructors();
            return View(NewInstructor);
        }

        // POST: Instructors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Instructors instructors)
        {
            if (instructors.Id == 0)
            {
                instructors.UserId = User.Identity.GetUserId();
                db.Instructors.Add(instructors);
                db.SaveChanges();
                return RedirectToAction("Index", "Students");
            }

            return View(instructors);
        }

        // GET: Instructors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructors instructors = db.Instructors.Find(id);
            if (instructors == null)
            {
                return HttpNotFound();
            }
            return View(instructors);
        }

        // POST: Instructors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Instructors instructors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instructors).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Students");
            }
            return View(instructors);
        }

        // GET: Instructors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructors instructors = db.Instructors.Find(id);
            if (instructors == null)
            {
                return HttpNotFound();
            }

            db.Instructors.Remove(instructors);
            db.SaveChanges();
            return RedirectToAction("Index", "Students");
        }

        protected void CheckIfStudentPassed(Students_Lectures Student)
        {
            var AttendedStudent = db.Students_Lectures.SingleOrDefault(z => z.StudentId == Student.StudentId && z.LectureId == Student.LectureId);

            if (AttendedStudent.IsCodeCorrect == true && AttendedStudent.IsShortAnswerCorrect == true)
            {
                AttendedStudent.CompletedCourse = true;
            }
            else
            {
                AttendedStudent.CompletedCourse = false;
            }
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapStonePhase2/Controllers/LecturesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CapStonePhase2.Models;
using System.CodeDom.Compiler;
using Microsoft.CSharp;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Collections.Generic;
using System;

namespace CapStonePhase2.Controllers
{
    public class LecturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Lectures
        public ActionResult Index()
        {
            return View(db.Lectures.ToList());
        }

        public ActionResult Description(int studentid, int lectureid)
        {
            var AttendingStudent = db.Students.SingleOrDefault(z=>z.Id == studentid);

            var PriorStudent = db.Students_Lectures.Include(x=>x.Lecture).Include(y=>y.Student).SingleOrDefault(z => z.StudentId == studentid && z.LectureId == lectureid);

            if (PriorStudent == null)
            {
                PriorStudent = NewStudentInLecture(studentid, lectureid);
            }

            if (AttendingStudent != null)
            {
                AttendingStudent.Lectureid = lectureid;
            }

            db.SaveChanges();
            return View(PriorStudent);
        }


        public ActionResult ReviewQuestion(int studentid, int lectureid)
        {
            var AnsweredStudent = db.Students_Lectures.Include(y=>y.Lecture).SingleOrDefault(z => z.StudentId == studentid && z.LectureId == lectureid);

            if (AnsweredStudent == null)
            {
                AnsweredStudent = NewStudentInLecture(studentid, lectureid);
            }

            return View(AnsweredStudent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReviewQuestion(Students_Lectures StudentAnswers)
        {
            var EnteredStudent = db.Students_Lectures.SingleOrDefault(z=>z.StudentId == StudentAnswers.StudentId && z.LectureId == StudentAnswers.LectureId);

            if(EnteredStudent == null)
            {
                return HttpNotFound();
            }

            EnteredStudent.ShortAnswer = StudentAnswers.ShortAnswer;

            db.SaveChanges();
            return RedirectToAction("CodeAssignment", new { studentid = EnteredStudent.StudentId, lectureid = EnteredStudent.LectureId });
        }

        
        public ActionResult CodeAssignment(int studentid, int lectureid)
        {
            var StudentAnswers = db.Students_Lectures.Include(x => x.Lecture).Include(y => y.Student).SingleOrDefault(z => z.StudentId == studentid && z.LectureId == lectureid);

            if (StudentAnswers == null)
            {
                StudentAnswers = NewStudentInLecture(studentid, lectureid);
            }

            StudentAnswers.CodeFileName = CreateNewStudentCodeFile(StudentAnswers);
            StudentAnswers.MethodsAndReturnValues = db.Methods.Where(x => x.Lectureid == lectureid).ToList();

            if(StudentAnswers.CodeFileText == null || StudentAnswers.CodeFileText == "")
            {
                StudentAnswers.CodeFileText = CreateMethodTemplate();
            }
            
            db.SaveChanges();
            return View(StudentAnswers);
        }

        [HttpPost]
        public ActionResult CodeAssignment(int lectureId, int studentId, string CodeFileText)
        {
            var StudentCodeAnswers = db.Students_Lectures.Include(x => x.Lecture).SingleOrDefault(x => x.LectureId == lectureId && x.StudentId == studentId);

            InsertStudentCode(StudentCodeAnswers, CodeFileText);

            return RedirectToAction("Compiler", new { filename = StudentCodeAnswers.CodeFileName });
        }

        public ActionResult Compiler(string filename)
        {
            string CodeFile = System.IO.File.ReadAllText($@"{ filename }");
            var results = CompileCsharpSource(new[] { CodeFile }, "App.exe");

            var  CompilerFeedback = InsertErrors(results.Errors);

            return View(CompilerFeedback);
        }

        // GET: Lectures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lectures lectures = db.Lectures.Find(id);
            if (lectures == null)
            {
                return HttpNotFound();
            }
            return View(lectures);
        }

        // GET: Lectures/Create
        public ActionResult Create()
        {
            Lectures NewLecture = new Lectures();
            return View(NewLecture);
        }

        // POST: Lectures/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Lectures lectures)
        {
            if (ModelState.IsValid)
            {
                db.Lectures.Add(lectures);
                db.SaveChanges();

                var NewLecture = db.Lectures.SingleOrDefault(x=>x.Id == lectures.Id);

                return RedirectToAction("CreateNewTest", new { lectureid = NewLecture.Id });
            }

            return View(lectures);
        }

        public ActionResult CreateNewTest(int lectureid)
        {
            var Lecture = db.Lectures.Find(lectureid);

            if (Lecture.CodeFileName == null || Lecture.CodeFileName == "")
            {
                Lecture.CodeFileName = GenerateNewTestFile(Lecture.Topic);
                Lecture.CodeFileText = GetFileText(Lecture.CodeFileName);
            }
            db.SaveChanges();

            return View(Lecture);
        }

        [HttpPost]
        public ActionResult CreateNewTest(Lectures lecture)
        {
            var LectureInDB = db.Lectures.Find(lecture.Id);

            LectureInDB.CodeFileText = lecture.CodeFileText;
 
            UpdateCodeFile(LectureInDB.CodeFileName, LectureInDB.CodeFileText);


            List<string> Lines = System.IO.File.ReadAllLines(LectureInDB.CodeFileName).ToList();

            List<string> LinesWithoutMainMethod = FilterOutMainMethod(Lines);

            List<string> ListOfMethodNames = StartFindingMethods(LinesWithoutMainMethod);


            InsertNewMethods(ListOfMethodNames, LectureInDB);

            db.SaveChanges();
            return RedirectToAction("ConfigureMethods", new { id = LectureInDB.Id });
        }

        public ActionResult ConfigureMethods(int id)
        {
            var MethodsInLectureTest = db.Methods.Where(x => x.Lectureid == id).ToList();

            if (MethodsInLectureTest == null)
            {
                return HttpNotFound();
            }

            return View(MethodsInLectureTest);
        }

        [HttpPost]
        public ActionResult ConfigureMethods(List<Methods> UpdatedMethods)
        {
            var FirstMethod = UpdatedMethods.FirstOrDefault();

            if(FirstMethod == null)
            {
                return HttpNotFound();
            }

            var MethodsInDB = db.Methods.Where(x => x.Lectureid == FirstMethod.Lectureid).ToList();

            for (int index = 0; index < UpdatedMethods.Count(); index++)
            {
                if(MethodsInDB[index].Id == UpdatedMethods[index].Id)
                {
                    MethodsInDB[index].ReturnValueType = UpdatedMethods[index].ReturnValueType;
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Lectures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lectures lectures = db.Lectures.Find(id);
            if (lectures == null)
            {
                return HttpNotFound();
            }
            return View(lectures);
        }

        // POST: Lectures/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Lectures lectures)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lectures).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lectures);
        }

        public ActionResult LectureTest(int id)
        {
            var Lecture = db.Lectures.Find(id);

            if(Lecture == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(Lecture);
        }

        [HttpPost]
        public ActionResult LectureTest(Lectures UpdatedTestFile)
        {
            var LectureinDB = db.Lectures.Find(UpdatedTestFile.Id);

            LectureinDB.CodeFileText = UpdatedTestFile.CodeFileText;
            db.SaveChanges();
            
            UpdateCodeFile(LectureinDB.CodeFileName, LectureinDB.CodeFileText);

            return RedirectToAction("Index");
        }

        // GET: Lectures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lectures lectures = db.Lectures.Find(id);
            if (lectures == null)
            {
                return HttpNotFound();
            }
            db.Lectures.Remove(lectures);
            db.SaveChanges();
            return RedirectToAction("Index");
        } 

        protected void InsertStudentCode(Students_Lectures StudentCode, string CodeFileText)
        {
            var LectureTest = db.Lectures.Find(StudentCode.LectureId);
            List<string> MainMethod = GetMainMethod(LectureTest.CodeFileName);

            UpdateCodeFile(StudentCode.CodeFileName, CodeFileText);

CapStonePhase2/Views/Students/CompletedCourses.cshtml
@model IEnumerable<CapStonePhase2.Models.Students_Lectures>
@using CapStonePhase2.CustomHelpers

@{
    ViewBag.Title = "Completed Courses";
}

<h2>@foreach (var item in Model)
{
    @Html.DisplayFor(modelItem => item.Student.FirstName)
    <i>  </i>
    @Html.DisplayFor(modelItem => item.Student.LastName)
    break;
}</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Lecture.Topic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompletedCourse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsShortAnswerCorrect)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCodeCorrect)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Lecture.Topic)
            </td>
            <td>
                @Html.BoolToString(item.CompletedCourse)
            </td>
            <td>
                @Html.BoolToString(item.IsShortAnswerCorrect)
            </td>
            <td>
                @Html.BoolToString(item.IsCodeCorrect)
            </td>
            <td>
                @Html.ActionLink("Grade Short Answer", "GradeShortAnswer", "Instructors", new { studentid = item.StudentId, lectureid = item.LectureId }, null)
            </td>
        </tr>
    }

</table>

CapStonePhase2/Views/Students/Create.cshtml
@model CapStonePhase2.Models.Students

@{
    ViewBag.Title = "Welcome New Student";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapStonePhase2/Views/Students/Details.cshtml
@model CapStonePhase2.Models.Students

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Students</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dd>
            @Html.DisplayNameFor(model => model.CompletedLectures)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.CompletedLectures)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CapStonePhase2/Views/Students/Edit.cshtml
@model CapStonePhase2.Models.Students

@{
    ViewBag.Title = "Edit";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Students</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapStonePhase2/Views/Students/Grade.cshtml
@model CapStonePhase2.Models.Students_Lectures
@using CapStonePhase2.CustomHelpers


@{
    ViewBag.Title = "Grade";
}

<h2>@Html.DisplayFor(model => model.Lecture.Topic)</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IsShortAnswerCorrect)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCodeCorrect)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompletedCourse)
        </th>
        <th></th>
    </tr>
        <tr>
            <td>
                @Html.BoolToString(Model.IsShortAnswerCorrect)
            </td>
            <td>
                @Html.BoolToString(Model.IsCodeCorrect)
            </td>
            <td>
                @Html.BoolToString(Model.CompletedCourse)
            </td>
        </tr>

</table>

CapStonePhase2/Views/Students/Index.cshtml
@model IEnumerable<CapStonePhase2.Models.Students>

@{
    ViewBag.Title = "Students";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("View Completed Courses", "CompletedCourses", new { studentid = item.Id }) |
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CapStonePhase2/Views/Students/Lectures.cshtml
@model IEnumerable<CapStonePhase2.Models.Lectures>

@{
    ViewBag.Title = "Lectures";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Topic, "Description", "Lectures", new { studentid = item.StudentId, lectureid = item.Id }, null)  |   
            @Html.ActionLink("View Grade", "Grade", new { studentid = item.StudentId, lectureid = item.Id })
        </td>
    </tr>
}

</table>

CapStonePhase2/Views/Students/ViewCompletedCourses.cshtml
@model IEnumerable<CapStonePhase2.Models.Students_Lectures>
@using CapStonePhase2.CustomHelpers

@{
    ViewBag.Title = "CompletedCourses";
}

<h2>Progress Report</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Lecture.Topic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompletedCourse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsShortAnswerCorrect)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCodeCorrect)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Lecture.Topic)
        </td>
        <td>
            @Html.BoolToString(item.CompletedCourse)
        </td>
        <td>
            @Html.BoolToString(item.IsShortAnswerCorrect)
        </td>
        <td>
            @Html.BoolToString(item.IsCodeCorrect)
        </td>
     </tr>
}

</table>